#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

if [ ! -d "$VENV_NAME" ]; then
    echo "Setting up virtualenv in $VENV_NAME"
    python3 -m venv $VENV_NAME
fi

source "$VENV_NAME/bin/activate"

echo "Installing dependencies"
pip install -e ".[dev]"

echo ""
echo "Run source $VENV_NAME/bin/activate to get your shell into the virtualenv"
echo "See README.md for more information."
echo ""
