#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

source "$VENV_NAME/bin/activate"

SOURCE_DIR="octodns_domeneshop/"

pytest \
  --disable-network \
  --cov-reset \
  --cov=$SOURCE_DIR \
  --cov-report=html \
  --cov-report=xml \
  --cov-report=term \
  --cov-branch \
  "$@"
